CREATE TABLE IF NOT EXISTS hivelab.pageuser(userid BIGINT,
  gender STRING,
  age INT)
COMMENT 'This is the page user table'
ROW FORMAT DELIMITED
  FIELDS TERMINATED BY '\t'
  COLLECTION ITEMS TERMINATED BY ','
  MAP KEYS TERMINATED BY ':'
STORED AS TEXTFILE;
